### ISSUE TITLE
Xcode 6.2 beta support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [kattrali/deriveddata-exterminator#29]
The plugin doesn't work in Xcode 6.2 beta or beta 2. The menu items aren't appearing.

**Comment by marcoscurvello** [comment]
I know support for xcode 6.2 will be added soon, but in the meantime what UUID can we add to the `DVTPlugInCompatibilityUUIDs` array ?

**Comment by Isuru-Nanayakkara** [comment]
A16FF353-8441-459E-A50C-B071F53F51B7

To check the UDID of your current Xcode:
```
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
```

[Source](https://github.com/supermarin/Alcatraz/issues/203#issuecomment-77978461)

**Comment by kattrali** [comment]
Updated for Xcode 6.2 GM.

**Comment by X-man-rascal** [comment]
I use Xcode6.2GM add this UDID then Xcode  crash，Don't launch

**Comment by kattrali** [comment]
@X-man-rascal Please open a new issue with a stacktrace if you are having trouble.
