### ISSUE TITLE
DMMButtonViewController causes Xcode 7 to crash

### ISSUE THREAD

**Issue by fbara** [kattrali/deriveddata-exterminator#37]
This control was installed on my system when I added the deriveddata-exterminator via Alcatraz.  I'm running OS X v10.10.4 and have both Xcode 6.4 and 7 beta 2.

I can open and close projects without a problem in Xcode 6.4 and earlier.  I can open projects in Xcode 7 but when I close the project Xcode crashes.  Here's the portion of the crash log where I found the issue:

	Application Specific Information:
	ProductBuildVersion: 7A121l
	UNCAUGHT EXCEPTION 	(NSInternalInconsistencyException): -[NSNib initWithNibNamed:bundle:] could not load the nibName: DMMButtonViewController in bundle (null).
	UserInfo: (null)
	Hints: None

I searched my system for DMMButtonViewController and the only place it was located was within derived data-exterminator.  I removed it via Alcatraz, restarted Xcode 7, open and closed projects, didn't get any crashes.

**Comment by Hs-Yeah** [comment]
:+1:

**Comment by smileyborg** [comment]
Same issue. Here's the [full crash report](https://gist.github.com/smileyborg/e346d0de0dff0676ef4f).
