### ISSUE TITLE
Icon and Menu Options missing in Xcode 7 GM

### ISSUE THREAD

**Issue by ArtSabintsev** [kattrali/deriveddata-exterminator#40]
The plugin is visible via Alcatraz, but the options and button are not found under the View menu.

Thanks for all your work on this add-on - much easier than opening up terminal :)

**Comment by kreeger** [comment]
For now you may need to pull down the code from `master` and build it. I don't know if the latest release is in Alcatraz yet, but `master` works just fine if you clone and build yourself.

**Comment by ArtSabintsev** [comment]
thanks @kreeger - will do just that.

**Comment by ArtSabintsev** [comment]
hey, what do you know, it randomly just started working through Alcatraz when I restarted Xcode.

Closing this issue.

**Comment by edwinbosire** [comment]
I probably shouldn't be complaining as I am using beta software, but This doesn't work on Xcode 7.1 Beta

**Comment by kattrali** [comment]
@edwinbosire Oh no! It should work, can you try reinstalling it (in case the update hasn't been applied to your system yet), and otherwise open a new issue?
