### ISSUE TITLE
when i user the clean  my  works cannot be compiled.

### ISSUE THREAD

**Issue by TheCodeor** [kattrali/deriveddata-exterminator#48]
error: /Users/jadefan/Library/Developer/Xcode/DerivedData/StarKnowledge-fyydldzdmkvtxjgfogktxpqalmnx/Build/Products/Debug-iphoneos/Charts.framework: No such file or directory

why!!!!!!

**Comment by kattrali** [comment]
Xcode doesn't expect derived data to be removed this way, and occasionally takes a second to recover. Maybe retry or post the complete message from Console.app if the issue persists.
