### ISSUE TITLE
Can I run it as a command line in terminal ?

### ISSUE THREAD

**Issue by biolinh** [kattrali/deriveddata-exterminator#50]

**Comment by kattrali** [comment]
Hello! You cannot run the plugin in a terminal, but you can delete your derived data folder(s) directly. To delete the contents of the default derived data location:

```
rm -r ~/Library/Developer/Xcode/DerivedData/[app name]-[unique id]
```

or you can remove `[app name]-[unique id]` to delete all derived data.

Check your settings in Xcode to ensure this is the location you are using to store derived data. The global setting is in `Preferences > Locations > Derived Data`, or it can be customized per-project in `File > Workspace Settings… > Derived Data`.
